config/routes.rb
FinalProject::Application.routes.draw do
  get "club/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/sign_up', :to => 'pages#sign_up'
    
  root :to => 'pages#home'
  
  resources :users
  match '/signup',  :to => 'users#new'
  

end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name,	:presence   => true,
						:length	    => { :maximum => 50 }
	validates :email, 	:presence   => true,
						:format     => { :with => email_regex },
						:uniqueness => { :case_sensitive => false }
	# Automatically create the virtual attribute 'password_confirmation'.
	validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
	
	before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
	
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  def new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Home"
  end

  def login
	@title = "Login"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to University Sports!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
 
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
	
	def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis
	def title								# Method definition
		base_title = "University Sports"	# Variable assignment
		if @title.nil?						# Boolean test for nil
			base_title						# Implicit return
		else								
			"#{base_title} | #{@title}"		# String interpolation
		end
	end
	
  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
	
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    @current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user 
    @current_user ||= user_from_remember_token 
  end 
  
  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

	def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
	
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/club/new.html.erb
<h1>Club#new</h1>
<p>Find me in app/views/club/new.html.erb</p>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'style', :media => 'screen' %>
<%= stylesheet_link_tag 'style', :media => 'print' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University Sports | <%= @title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :application %>
  </head>
  <body>
    <div id="wrap">

<div id="header">

</div>

<div id="intro"> 


<%= image_tag("logo.jpg", :alt => "logo", :class => "round", :align => "right") %>

<h1>University Sports</h1><br />
<h2>A site to help manage your sports team</h2>

<div id="footer">

<table width="720">

<td width="75" align="center"><%= link_to "Home", '/' %></td>

<% if signed_in? %>
<td width="75" align="center"><%= link_to "Find Club", '#' %></td>
<td width="75" align="center"><%= link_to "Find User", users_path %></td>
<td width="75" align="center"><%= link_to "Profile", current_user %></td>
<% else %>
<td width="75" align="center"><%= link_to "Sign Up", 'signup' %></td>
<% end %>

<% if signed_in? %>
<td width="75" align="center"><%= link_to "Sign out", signout_path, :method => :delete %></td>
<% else %>
<td width="75" align="center"><%= link_to "Login", 'signin' %></td>
<% end %>

</table>

</div>

</div>

<div id="content">
<div class="left"> 

<h2><%= @title %></h2>

<div class="articles">

      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
</div>

</div>

<div class="right"> 

<!--<img src="#" border="0" ></a><br />
-->

<% if signed_in? %>
<%= link_to "Settings", edit_user_path(current_user) %>
<% else %>

<h2>Links</h2>

<a href="http://www.ausa.org.uk/sport">AUSA Sports</a> <br>
<a href="http://www.aberdeensportsvillage.com/">Aberdeen Sports Village</a> <br>
<a href="#"></a> <br>
<a href="#"></a> <!this is a filler space so that all menus are same size!> <BR> 
<% end %>

</div>

<div style="clear: both;"> </div>

</div>

<div id="footer">

<a href="http://www.abdn.ac.uk">Aberdeen University</a> <div id="copyright">Copyright &copy; 2011 Louis Griffiths</div>

</div>
      <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>



app/views/pages/home.html.erb
<p>
University sports is here to help you manage your univeristy sports team.
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  | <%= link_to "delete", user, :method => :delete, :confirm => "Are you sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
	  <div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	  </div>
	  <div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	  </div>
	  <div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	  </div>
	  <div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	  </div>
	  <div class="actions">
		<%= f.submit "Sign up" %>
	  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
      </h1>
    </td>
  </tr>
</table>